### ISSUE TITLE
Shutter status not correct

### ISSUE THREAD

**Issue by Notrial** [W00D00/home-assistance-elero#1]
After using shutter controls for a while, shutter status in Home Assistant stops showing actual values.
It starts switching from open to close and vice versa indefinitely (until you use cover.stop service).

That is a pretty big issue, since HA doesn't have the actual state and therefore you can't open a shutter which appears to be open already (although is closed).

Problem becomes even bigger if you control a group (I have 10 shutters), then there is simply no way to control them all at once.

Great first build though :) Really appreciate the effort!

**Comment by mkuoppa** [comment]
I'm experiencing something similar. From the Hans log file I get:
`WARNING (SyncWorker_16) [custom_components.cover.elero] unknown response: b''`
`WARNING (SyncWorker_16) [custom_components.cover.elero] Unhandled response: unknown response`

**Comment by W00D00** [comment]
Hi,

Please try the lates version and share your experiences. I hope this issue is solved.

Thanks,
